# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’
source 'https://github.com/WildDogTeam/wilddog-ios-repo.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'video-demo-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WilddogVideo’,’1.2.6’
  pod 'MBProgressHUD'
  pod 'TUSDK','0.0.1'
  pod 'PGSkinPrettifyEngine','0.0.1'
  
  pod 'Fabric'
  pod 'Crashlytics'
end
