# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/WildDogTeam/wilddog-ios-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'video-demo-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  #  白板
  pod 'WilddogBoard'
  pod 'Qiniu' , '7.1.7'
  #  wilddog sdk
  pod 'WilddogVideoCall’
  pod 'WilddogSync'
  pod 'WilddogVideoRoom'
  #  美颜
  pod 'TUSDK','0.0.1'
  pod 'GPUImage',:git=>'https://github.com/BradLarson/GPUImage.git'
  pod 'PGSkinPrettifyEngine','0.0.1'
  #  日志
  pod 'Fabric'
  pod 'Crashlytics'
  #微信登陆
  pod 'WechatOpenSDK'
  #个推
  pod 'GTSDK'
  #
  pod 'MBProgressHUD'
  pod 'SDWebImage'
end
